services:
  - type: web
    name: real-estate-mern-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    envVars:
      - key: VITE_API_URL
        value: https://real-estate-mern-backend-65vj.onrender.com/api
      - key: VITE_MAP_BOX_TOKEN
        value: pk.eyJ1IjoibWNsZWUyMTIxIiwiYSI6ImNsenliNG1mYTB4N3YybnNiODhld2lhcGgifQ.EuJtAs4dJvSA-ILwYbHDeQ
